---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _posts
  label: Commentaries
  create: all
  match: "**/*"
  templates:
  - test-post
- type: document
  path: NETLIFY.md
  label: Build Status
  read_only: true
- type: directory
  path: _spotlights
  label: Spotlights
  create: all
  match: "**/*"
  templates:
  - spotlights
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: data
- type: document
  path: _data/keywords.yml
  label: Keywords
- type: document
  path: _data/language.yml
  label: Language
- type: document
  path: _data/menus.yml
  label: Menus
upload_dir: ocean
public_path: https://res.cloudinary.com/csisideaslab/image/upload
front_matter_path: https://res.cloudinary.com/csisideaslab/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
